### ISSUE TITLE
Thank you guys for everything (:

### ISSUE THREAD

**Issue by xbox0** [tfdsoft/famidash#275]
you see, I get that Kando doesn't want to see me around in any of his servers anymore, I get it. I was pretty annoying. But I just want to say, thank you for accepting me into the community while I was there, and I'm glad to see that the project got finished. As for me, I've joined a new dev team and have an important role in it! It was nice being in the FamiDash Community while it lasted, and I hope you guys are doing well.

-the Xbox guy

**Comment by LNLenost** [comment]
I could say the exact same thing :)

**Comment by xbox0** [comment]
i havent been on the server for a while due to my ban, but thats okay!

**Comment by Maxiwah** [comment]
> you see, I get that Kando doesn't want to see me around in any of his servers anymore, I get it. I was pretty annoying. But I just want to say, thank you for accepting me into the community while I was there, and I'm glad to see that the project got finished. As for me, I've joined a new dev team and have an important role in it! It was nice being in the FamiDash Community while it lasted, and I hope you guys are doing well.
> 
> -the Xbox guy

**Comment by Maxiwah** [comment]
This is Maxiwah. Remember. How we both raced to beat Jumper in So Retro/Retro Mode? Hope ya doing well. :D

**Comment by xbox0** [comment]
Thanks, yes, i am doing well (:

**Comment by xbox0** [comment]
I'm now a BFDI Branches Plus dev (: How about you?

**Comment by Maxiwah** [comment]
Glad to hear. Oh, and I beat all of the other levels with it. I'm actually making Hexagon Force in the TILED level editor. I volunteered. Lol.

**Comment by Maxiwah** [comment]
I'M A FAN OF BFDI YAYAYAYAYA

**Comment by LNLenost** [comment]
> -the Xbox guy

Never heard of you ngl, what happened?

Ps welcome to the kando's nightmares club

**Comment by kandowontu** [comment]
Even though things didn't end up well with some of you, I still appreciate all of your support. Thanks guys, I do hope you enjoy the game!

**Comment by xbox0** [comment]
> > -the Xbox guy
> 
> Never heard of you ngl, what happened?
> 
> Ps welcome to the kando's nightmares club

basically, i did some annoying things, and got banned.

**Comment by LNLenost** [comment]
Ohh me too
