### ISSUE TITLE
Famidash 1.0 D-Pad Bugging out

### ISSUE THREAD

**Issue by axel61311** [tfdsoft/famidash#276]
**Describe the bug**
On both keyboard and controller, on both the menu and level select screen, The dpad and arrows both bug out, and they move on their own. The keyboard and controller both work fine, but it is only on this version that I am having issues on.

**Emulator(please complete the following information):**
 - iMac, Hori Controller Pad
 -OpenEmu

**Comment by kandowontu** [comment]
This is a bug that happens on inaccurate emulators. Sadly you’ll need to try a different emulator like mesen.

**Comment by kandowontu** [comment]
Actually I believe that OpenEMU allows you to change your NES core...try the FCEUX core!
