### ISSUE TITLE
Famidash bugged asf on 3DS Virtual Console

### ISSUE THREAD

**Issue by LukaTV939** [tfdsoft/famidash#277]
https://files.catbox.moe/adiua1.mp4

**Comment by kandowontu** [comment]
This homebrew is optimized for real hardware and makes use of a number of tricks and features that are not supported on that emulator. Sorry!

**Comment by jaezudev** [comment]
TL;DR skill issue. Use a better emulator

**Comment by LukaTV939** [comment]
> This homebrew is optimized for real hardware and makes use of a number of tricks and features that are not supported on that emulator. Sorry!

NES Virtual Console is litteraly developed by nintendo but ok

**Comment by LukaTV939** [comment]
Tho what is the recommend emulator to play on?

**Comment by kandowontu** [comment]
> > This homebrew is optimized for real hardware and makes use of a number of tricks and features that are not supported on that emulator. Sorry!
> 
> NES Virtual Console is litteraly developed by nintendo but ok

Canoe is far from perfect, and is written with particular games in mind, with quick patches being done to make other games work. It is not an accurate emulator for the NES.

**Comment by kandowontu** [comment]
> Tho what is the recommend emulator to play on?

Mesen

**Comment by LukaTV939** [comment]
> > Tho what is the recommend emulator to play on?
> 
> Mesen

I think I tried mesen core on retroarch but got no sound, do you know a fix?

**Comment by jaezudev** [comment]
Use Mesen itself, not some core on RetroArch

**Comment by kandowontu** [comment]
> > > Tho what is the recommend emulator to play on?
> > 
> > 
> > Mesen
> 
> I think I tried mesen core on retroarch but got no sound, do you know a fix?

I used it with no issues…try wiping your save in the settings menu

**Comment by iProgramMC** [comment]
> NES Virtual Console is litteraly developed by nintendo but ok

Nintendo is the prime example of console manufacturers who don't know their own consoles. The emulators only serve to emulate the games they made... and that's it. Third party titles they didn't account for, and especially homebrew, may have issues.

Not to mention, their N64 emulators aren't accurate even in first party games.

**Comment by NINJACLUBREAL** [comment]
use virtuanes emulator, it is on universal updater! It runs the game perfectly
