### ISSUE TITLE
Menu selector acting wierd

### ISSUE THREAD

**Issue by FireDasher** [tfdsoft/famidash#278]
**Describe the bug**
Whenever the menu is open, the selector just goes back and forth when I'm not pressing anything and it's SO annoying!

**How to reproduce**
Just open Famidash and go to the menu

**Emulator(please complete the following information):**
 - Device: [e.g. PC, Phone]: iPad
 - Emulator [e.g. RetroArch, Mesen]: Delta for iOS

**Comment by jaezudev** [comment]
Delta sucks ass, use a better one like Mesen or FCEUX

**Comment by kandowontu** [comment]
> **Describe the bug** Whenever the menu is open, the selector just goes back and forth when I'm not pressing anything and it's SO annoying!
> 
> **How to reproduce** Just open Famidash and go to the menu
> 
> **Emulator(please complete the following information):**
> 
> * Device: [e.g. PC, Phone]: iPad
> * Emulator [e.g. RetroArch, Mesen]: Delta for iOS

Use retroarch
