### ISSUE TITLE
Editor Levels

### ISSUE THREAD

**Issue by TheBoxGame** [tfdsoft/famidash#279]
Hello, I have a question. Will there be a level editor added to this game to make my own level?

**Comment by FicusmcHousePlant** [comment]
Yes, there is an external editor planned for the game which can be used to make level carts.

**Comment by TheBoxGame** [comment]
> Tak, planowany jest zewnętrzny edytor, który będzie można wykorzystać do tworzenia pakietów poziomów.

Thanks like this game and music

**Comment by kandowontu** [comment]
What we use for level editing is TILED, which is a freeware program. That will open our level TMX files.

On our discord, we have a channel with a brief tutorial of making and testing levels.
