### ISSUE TITLE
Eon crash

### ISSUE THREAD

**Issue by Crafty-Jumper** [tfdsoft/famidash#288]
**Describe the bug**
Eon crashes whenever you cursed music on

**How to reproduce**
1. Unlock fun settings
2. Turn on cursed music
3. load eon
4. crash game
3 alt. Goto soundtest
4 alt. Play eon song
5 alt. Crash game
**Screenshots e/o videos**

**Emulator(please complete the following information):**
 - Device: NES Classic Mini
 - Emulator RetroArch
 - Core: NES / Famicom (FCEUmm)

**Comment by kandowontu** [comment]
Yeah this was due to a poor export; it has been fixed in the nightly! 
https://nightly.link/tfdsoft/famidash/workflows/main/main/famidash.nes.zip
