### ISSUE TITLE
Inject crashes my 3DS

### ISSUE THREAD

**Issue by BarOSGithub** [tfdsoft/famidash#293]
**Describe the bug**
When launching my 3DS inject, it crashes

**How to reproduce**
![image](https://github.com/user-attachments/assets/d48ac96d-facb-4547-8faf-53604a491e31)
Follow these steps, Use Alt 2,

**Screenshots e/o videos**
Sorry, i dont have videos

**Emulator(please complete the following information):**
 - Device: Nintendo 3DS
 - Emulator: Injected CIA
 - Core [ONLY if you use RetroArch]: None

**Comment by kandowontu** [comment]
We do not officially support this. Unofficially some people on our discord have been able to properly get it to work.

Please join the discord and someone may be able to help at some point.
